---
##############################################################################
## Creates an OpenShift OpenWhisk template file from a Jinja2 template
##############################################################################
- name: Create OpenWhisk Openshift template from template
  template:
    src: openwhisk-template.j2
    dest: /tmp/openwhisk-template.yml

##############################################################################
## Provision OpenWhisk from yaml definition
##############################################################################
- name: Provision OpenWhisk from template
  shell: oc process -f /tmp/openwhisk-template.yml -n {{ namespace }} | oc create -f - -n {{ namespace }}


- name: Encode required Bind data
  asb_encode_binding:
    fields:
      namespace: "{{ namespace }}"
